describe("avoid_error", () => {
  Cypress.on("uncaught:exception", (err, runnable) => {
    return false
  })

  it("creates manual delivery", () => {
    cy.loginAdmin("admin@example.com", "Secret00")
    cy.chooseTeam("Testy automatyczne").then(() => {
      cy.navigateMenuTo("Zlecenia")
      cy.get('a[href="/admin/orders/new"').click()
      cy.get(".m-subheader__title").should("have.html", "Nowe zlecenie manualne")
      cy.get("#order_order_kind_pickup").click({ force: true })
      cy.get("#next-btn").click()
      cy.get("#spop--top-right").should("be.visible")
      cy.get("#select2-order_client_id-container").click()
      cy.get(".select2-results").should("be.visible")
      cy.get(".select2-results__option--highlighted").click()
      cy.get("#order_pickup_attributes_phone").should("not.have.value", "0")
      cy.get("#order_pickup_attributes_address").should("not.have.value", "0")
      cy.get("#order_pickup_in").type("20")
      cy.get("#order_pickup_at").should("not.have.value", "0")
      cy.get("#next-btn").click()
      cy.get("#spop--top-right").should("be.visible")
      cy.get("#order_bike_or_scooter_delivery_false").should("be.checked")
      cy.get(".m-option").contains("Zapłacone").click()
      cy.get("#order_price").type("{backspace}").type("50")
      cy.get("#next-btn").click()
      cy.get("#spop--top-right").should("be.visible")
      cy.get("#order_packages_big-pizza").type("1").should("have.value", "1")
      cy.get("#order_packages_standard-dish").type("1").should("have.value", "1")
      cy.get("#order_packages_own-packaging").type("1").should("have.value", "1")
      cy.get("#order_client_comment_attributes_description").should("be.enabled")
      cy.get("#order_customer_comment_attributes_description").should("be.enabled")
      cy.get("#order_order_comment_attributes_description").should("be.enabled")
      cy.get("#next-btn").click()
      cy.get("#spop--top-right").should("be.visible")
      cy.get(".btn-primary").click()
      cy.get(".m-subheader__title").should("have.html", "Zlecenia")
    })
  })
})
